# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Deploy On Push

    runs-on: ubuntu-latest
    if: ${{ github.repository == 'dsyer/enhance-llm' }}

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        tags: user/app:latest
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache LLM Data
      id: cache-models
      uses: actions/cache@v4
      with:
        path: ollama
        key: ${{ runner.os }}-models
    - name: Install with Maven
      run: |
          ./mvnw -B install

